#!/usr/bin/env python3
"""
work_range.py — креслення робочої зони у вигляді, який дають виробники екскаваторів:
контур зони, характерні пози машини, розмірні лінії з буквами і таблиця значень.

Геометрію бере з tools/kinematics.py (той самий GEOM, що звіряється з моделлю),
тож жодне число тут не вписане руками.

  tools/.venv/bin/python tools/work_range.py --out docs/img/work-range.png
  tools/.venv/bin/python tools/work_range.py --lang en --out docs/img/work-range.en.png

Межі зони рахуються перебором усіх трьох кутів (стріла × рукоять × ківш) і взяттям
максимального/мінімального радіуса від осі A за напрямком — зона в такої машини є
кільцевим сектором, тому в полярних координатах з центром у A вона однозначна.

Відліки: усе — від ОСІ A (шарнір стріли на колоні), а не від осі обертання машини,
бо поворотної платформи в моделі ще немає. Її виліт додасться до радіусів.
"""
import argparse
import math
import os
import sys
import textwrap

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kinematics as kin
import bucket as bkt
from shapely.ops import unary_union


def bucket_outline():
    """Силует ковша у власній системі (E = 0, x — до зуба) з tools/bucket.py."""
    pr = bkt.profile(bkt.BUCKET, kin.GEOM)
    u = unary_union([pr['side'], pr['blade'], pr['tooth']])
    return list(zip(*u.exterior.xy))


BK = bucket_outline()


def place(poly, origin, a):
    """Силует у світових координатах: поворот на a° і перенос у origin."""
    return [kin.add(origin, kin.rot(p, a)) for p in poly]

WARN_UK = ('УВАГА: згенеровано штучним інтелектом, кваліфікований інженер не перевіряв, '
           'машину не збудовано й не випробувано. Див. SAFETY.md')
WARN_EN = ('WARNING: generated by AI, not reviewed by a qualified engineer, '
           'the machine has not been built or tested. See SAFETY.md')

T = {
    'uk': dict(
        title='Робоча зона',
        sub='міні-екскаватор (причіпний), ківш 300 мм · розміри в мм від осі A (шарнір стріли)',
        ground='рівень землі',
        axisA='вісь A\n(кріплення стріли)',
        table='Розміри робочої зони',
        note=('Контур — крайні положення вістря зуба на всьому ході трьох циліндрів. '
              'Радіуси відкладено від осі A: осі обертання машини в моделі ще немає, '
              'її виліт додасться до всіх горизонтальних розмірів.'),
        wallnote=('* стінка вважається зрізаною, коли вісь ковша відхилена від вертикалі '
                  'не більше ніж на 20°\n'
                  '** ківш розкрито повністю; міряється найнижча точка ковша, а не вістря зуба'),
        dims=dict(
            A='Макс. радіус копання',
            B='Радіус копання на рівні землі',
            C='Макс. глибина копання',
            D='Глибина вертикальної стінки *',
            E='Макс. висота копання (зуб)',
            F='Макс. висота вивантаження **',
            G='Висота осі A над землею',
            H='Мін. радіус на рівні землі',
            J='Макс. висота осі ковша E',
        ),
        poses=['макс. виліт', 'макс. глибина', 'макс. висота'],
    ),
    'en': dict(
        title='Working range',
        sub='towed mini excavator, 300 mm bucket · dimensions in mm from pin A (boom foot)',
        ground='ground level',
        axisA='pin A\n(boom foot)',
        table='Working range dimensions',
        note=('The outline is the extreme travel of the bucket tooth over the full stroke '
              'of all three cylinders. Radii are measured from pin A: the model has no '
              'slew centre yet, so its offset adds to every horizontal dimension.'),
        wallnote=('* a wall counts as cut when the bucket axis is within 20° of vertical\n'
                  '** bucket fully open; measured to the lowest point of the bucket, not the tooth'),
        dims=dict(
            A='Max digging reach',
            B='Digging reach at ground level',
            C='Max digging depth',
            D='Vertical wall digging depth *',
            E='Max digging height (tooth)',
            F='Max dumping height **',
            G='Boom foot pin A above ground',
            H='Min reach at ground level',
            J='Max bucket pin E height',
        ),
        poses=['max reach', 'max depth', 'max height'],
    ),
}


# ---------------------------------------------------------------- кінематика
def sweep(g, n_t=97, n_p=97, n_o=45):
    """Хмара положень вістря зуба на всьому ході трьох циліндрів."""
    th0, th1 = kin.boom_range(g)
    ps0, ps1 = kin.stick_range(g)
    _, om0, om1, _ = kin.bucket_range(g)
    out = []
    for t in kin.frange(th0, th1, n_t):
        bp = kin.boom_points(g, t)
        for p in kin.frange(ps0, ps1, n_p):
            sp = kin.stick_points(g, bp, p)
            for o in kin.frange(om0, om1, n_o):
                a = sp['a_s'] - o                      # напрямок осі ковша E→зуб
                tip = kin.add(sp['E'], kin.rot((g['tip'], 0), a))
                out.append(dict(x=tip[0], y=tip[1], axis=a, th=t, psi=p, om=o, E=sp['E']))
    return dict(pts=out, th=(th0, th1), ps=(ps0, ps1), om=(om0, om1))


def outline(pts, bins=540):
    """Зовнішня і внутрішня межі зони в полярних координатах з центром у осі A."""
    lo = [None] * bins
    hi = [None] * bins
    for p in pts:
        r = math.hypot(p['x'], p['y'])
        i = int((math.degrees(math.atan2(p['y'], p['x'])) + 180.0) / 360.0 * bins) % bins
        if hi[i] is None or r > hi[i]:
            hi[i] = r
        if lo[i] is None or r < lo[i]:
            lo[i] = r
    outer, inner = [], []
    for i in range(bins):
        if hi[i] is None:
            continue
        a = math.radians((i + 0.5) / bins * 360.0 - 180.0)
        outer.append((hi[i] * math.cos(a), hi[i] * math.sin(a)))
        inner.append((lo[i] * math.cos(a), lo[i] * math.sin(a)))
    return outer, inner


def cross_y(poly, y):
    """Найбільший x, де ламана перетинає горизонталь y (лінійна інтерполяція)."""
    best = None
    for (x0, y0), (x1, y1) in zip(poly, poly[1:]):
        if (y0 - y) * (y1 - y) <= 0 and abs(y1 - y0) > 1e-9:
            x = x0 + (x1 - x0) * (y - y0) / (y1 - y0)
            if best is None or x > best:
                best = x
    return best


def measures(g, sw, outer, inner):
    """Характерні розміри — усі з хмари положень, жодного вписаного руками."""
    pts = sw['pts']
    ground = -g['A_height']
    xs_ground = cross_y(outer, ground)
    xs_ground_in = cross_y(inner, ground)

    deepest = min(pts, key=lambda p: p['y'])
    highest = max(pts, key=lambda p: p['y'])
    farthest = max(pts, key=lambda p: p['x'])
    # Вивантаження: ківш розкрито повністю (omega на нижній межі ходу), і міряється
    # не зуб, а НАЙНИЖЧА точка ковша — під нею має пройти борт кузова.
    om0 = sw['om'][0]
    dump, dump_y = None, -1e9
    for p in pts:
        if abs(p['om'] - om0) > 1e-6:
            continue
        low = min(q[1] for q in place(BK, p['E'], p['axis']))
        if low > dump_y:
            dump, dump_y = p, low
    e_high = max(p['E'][1] for p in pts)

    # вертикальна стінка: вісь ковша ближча до вертикалі, ніж 20°, і зуб іде суцільним
    # стовпом від землі вниз. Крок стовпа 25 мм — дрібніше сітка положень не дає.
    step = 25.0
    wall = 0.0
    cols = {}
    for p in pts:
        d = abs(((p['axis'] + 90.0) % 180.0) - 90.0)    # відхилення осі ковша від вертикалі
        if d > 20.0 or p['y'] > ground:
            continue
        cols.setdefault(round(p['x'] / step), set()).add(round((ground - p['y']) / step))
    for levels in cols.values():
        if 0 not in levels:          # стовп має починатися від самої землі
            continue
        d = 0
        while (d + 1) in levels:     # і йти вниз без розривів
            d += 1
        wall = max(wall, d * step)

    return dict(
        A=(farthest['x'], farthest),
        B=(xs_ground, None),
        C=(ground - deepest['y'], deepest),
        D=(wall, None),
        E=(highest['y'] - ground, highest),
        F=(dump_y - ground, dump),
        G=(g['A_height'], None),
        H=(xs_ground_in, None),
        J=(e_high - ground, None),
    )


def pose(g, p):
    """Ламана стріла→рукоять і силует ковша для положення з хмари."""
    bp = kin.boom_points(g, p['th'])
    sp = kin.stick_points(g, bp, p['psi'])
    return [bp['A'], bp['K'], bp['B'], sp['E']], place(BK, sp['E'], p['axis'])


# ---------------------------------------------------------------- креслення
def draw(g, lang, out):
    t = T[lang]
    sw = sweep(g)
    outer, inner = outline(sw['pts'])
    m = measures(g, sw, outer, inner)
    ground = -g['A_height']

    fig = plt.figure(figsize=(16.5, 11.7))
    ax = fig.add_axes([0.05, 0.10, 0.66, 0.84])
    ax.set_aspect('equal')
    ax.axis('off')

    # --- зона
    poly = outer + inner[::-1]
    ax.fill([p[0] for p in poly], [p[1] for p in poly], color='#dfe9f5', ec='none', zorder=1)
    ax.plot([p[0] for p in outer], [p[1] for p in outer], color='#1f4e9c', lw=1.8, zorder=3)
    ax.plot([p[0] for p in inner], [p[1] for p in inner], color='#1f4e9c', lw=1.2, ls=(0, (6, 3)), zorder=3)

    # --- земля зі штриховкою
    x0, x1 = -1500, m['A'][0] + 700
    ax.plot([x0, x1], [ground, ground], color='#6b4f2a', lw=2.2, zorder=4)
    for x in range(int(x0), int(x1), 90):
        ax.plot([x, x - 60], [ground, ground - 60], color='#6b4f2a', lw=0.8, zorder=4)
    ax.text(x0 + 60, ground - 150, t['ground'], fontsize=9, color='#6b4f2a')

    # --- пози машини
    keys = [m['A'][1], m['C'][1], m['E'][1]]
    cols = ['#c8621a', '#2a7d2a', '#8a5bb5']
    for p, c, name in zip(keys, cols, t['poses']):
        arm, bk = pose(g, p)
        ax.plot([q[0] for q in arm], [q[1] for q in arm], color=c, lw=2.6, alpha=0.9,
                solid_capstyle='round', zorder=5, label=name)
        ax.plot([q[0] for q in arm], [q[1] for q in arm], 'o', color=c, ms=4, zorder=6)
        ax.fill([q[0] for q in bk], [q[1] for q in bk], fc=c, ec=c, alpha=0.35, lw=1.4, zorder=5)
    ax.legend(loc='lower left', fontsize=9.5, frameon=False, handlelength=1.6)

    # --- колона і вісь A
    ax.plot([0, 0], [ground, 0], color='0.35', lw=3.5, zorder=4)
    ax.plot([g['Cx'], 0], [g['Cy'], 0], color='0.35', lw=3.5, zorder=4)
    ax.add_patch(Circle((0, 0), 42, fc='w', ec='k', lw=1.6, zorder=7))
    ax.plot([0], [0], marker='+', ms=11, color='k', mew=1.4, zorder=8)
    ax.annotate(t['axisA'], (0, 0), xytext=(-560, 330), fontsize=9,
                arrowprops=dict(arrowstyle='->', lw=0.9), zorder=8)

    # --- розмірні лінії
    def letter(x, y, s):
        ax.add_patch(Circle((x, y), 62, fc='#1f4e9c', ec='none', zorder=9))
        ax.text(x, y, s, color='w', fontsize=10, weight='bold', ha='center', va='center', zorder=10)

    def dim_v(x, ya, yb, s, val):
        ax.plot([x, x], [ya, yb], color='#1f4e9c', lw=1.0, zorder=8)
        for y in (ya, yb):
            ax.plot([x - 55, x + 55], [y, y], color='#1f4e9c', lw=1.0, zorder=8)
        letter(x, (ya + yb) / 2, s)
        # число — біля дальнього кінця лінії, інакше сусідні розміри злипаються
        far = yb if abs(yb - ya) > 0 else ya
        ax.text(x - 70, far - math.copysign(130, yb - ya), f'{val:.0f}', fontsize=10,
                ha='center', va='center', rotation=90, color='#1f4e9c', zorder=8)

    def dim_h(y, xa, xb, s, val):
        ax.plot([xa, xb], [y, y], color='#1f4e9c', lw=1.0, zorder=8)
        for x in (xa, xb):
            ax.plot([x, x], [y - 55, y + 55], color='#1f4e9c', lw=1.0, zorder=8)
        xm = (xa + xb) / 2
        letter(xm, y, s)
        ax.text(xm, y + 110, f'{val:.0f}', fontsize=10, ha='center', va='bottom', color='#1f4e9c', zorder=8)

    top = ground + m['E'][0]
    bot = ground - m['C'][0]
    xE, xF, xJ, xG = -1560, -1240, -920, -600
    # виносні лінії від самої машини до розмірних
    for y, xr, xd in ((top, m['E'][1]['x'], xE), (ground + m['F'][0], m['F'][1]['x'], xF),
                      (ground + m['J'][0], 0, xJ), (0, 0, xG), (bot, m['C'][1]['x'], xE),
                      (ground - m['D'][0], 0, xF), (ground, 0, xE)):
        ax.plot([xd - 90, xr], [y, y], color='0.7', lw=0.6, ls=(0, (4, 4)), zorder=2)

    dim_v(xE, ground, top, 'E', m['E'][0])
    dim_v(xF, ground, ground + m['F'][0], 'F', m['F'][0])
    dim_v(xJ, ground, ground + m['J'][0], 'J', m['J'][0])
    dim_v(xG, ground, 0, 'G', m['G'][0])
    dim_v(xE, ground, bot, 'C', m['C'][0])
    dim_v(xF, ground, ground - m['D'][0], 'D', m['D'][0])

    ybase = bot - 420
    for x in (0, m['A'][0], m['B'][0], m['H'][0]):
        ax.plot([x, x], [ybase - 760, min(ground, bot)], color='0.7', lw=0.6, ls=(0, (4, 4)), zorder=2)
    dim_h(ybase, 0, m['A'][0], 'A', m['A'][0])
    dim_h(ybase - 340, 0, m['B'][0], 'B', m['B'][0])
    dim_h(ybase - 680, 0, m['H'][0], 'H', m['H'][0])

    ax.set_xlim(xE - 320, m['A'][0] + 750)
    ax.set_ylim(ybase - 950, ground + m['E'][0] + 400)

    # --- таблиця
    tx = 0.745
    fig.text(tx, 0.885, t['table'], fontsize=13, weight='bold')
    fig.text(tx, 0.862, 'мм' if lang == 'uk' else 'mm', fontsize=9.5, color='0.45')
    y = 0.820
    for k in 'ABCDEFGHJ':
        fig.text(tx, y, k, fontsize=10.5, weight='bold', color='w',
                 bbox=dict(boxstyle='circle,pad=0.3', fc='#1f4e9c', ec='none'))
        fig.text(tx + 0.026, y, t['dims'][k], fontsize=10, va='baseline')
        fig.text(0.985, y, f'{m[k][0]:.0f}', fontsize=11, weight='bold', ha='right', va='baseline')
        y -= 0.041
    # Перенесення вручну: шрифт пропорційний, довгі рядки мовчки вилазять за аркуш.
    wall = '\n'.join(textwrap.fill(s, 56) for s in t['wallnote'].split('\n'))
    fig.text(tx, y - 0.005, wall, fontsize=8.5, color='0.35', va='top', linespacing=1.6)
    fig.text(tx, y - 0.105, textwrap.fill(t['note'], 52), fontsize=9, color='0.25',
             va='top', linespacing=1.6)

    fig.text(0.05, 0.955, t['title'], fontsize=20, weight='bold')
    fig.text(0.05, 0.932, t['sub'], fontsize=10.5, color='0.3')
    fig.text(0.05, 0.035, (WARN_UK if lang == 'uk' else WARN_EN), fontsize=8.5, color='0.4')
    fig.text(0.05, 0.015, f'scad/excavator_boom.scad · tools/work_range.py', fontsize=8.5, color='0.55')

    fig.savefig(out, dpi=110)
    plt.close(fig)

    w = max(len(t['dims'][k]) for k in 'ABCDEFGHJ')
    print(f'{out}')
    for k in 'ABCDEFGHJ':
        print(f'  {k}  {t["dims"][k]:<{w}}  {m[k][0]:8.0f} {"мм" if lang == "uk" else "mm"}')
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--lang', default='uk', choices=['uk', 'en'])
    ap.add_argument('--out', default='docs/img/work-range.png')
    a = ap.parse_args()
    draw(kin.GEOM, a.lang, a.out)


if __name__ == '__main__':
    main()
